# Generated by Django 5.1.3 on 2024-11-27 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('established_year', models.PositiveIntegerField()),
                ('home_ground', models.CharField(max_length=255)),
                ('total_matches_played', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('total_losses', models.PositiveIntegerField(default=0)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('team_color', models.CharField(blank=True, max_length=50, null=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='common.person')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to='common.person')),
                ('players', models.ManyToManyField(limit_choices_to={'role': 'player'}, related_name='teams', to='common.person')),
            ],
            options={
                'verbose_name': 'Cricket Team',
                'verbose_name_plural': 'Cricket Teams',
            },
        ),
    ]
