# Generated by Django 5.1.3 on 2024-11-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_person_extra_data_remove_person_is_active'),
        ('league_sphere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketteam',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_cricket_teams', to='common.country'),
        ),
    ]
