# Generated by Django 5.1.3 on 2024-11-29 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_role_alter_person_role'),
        ('league_sphere', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketteam',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='common.person'),
        ),
        migrations.AlterField(
            model_name='cricketteam',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_teams', to='common.person'),
        ),
        migrations.AlterField(
            model_name='cricketteam',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_cricket_teams', to='common.country'),
        ),
        migrations.AlterField(
            model_name='cricketteam',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cricket_teams', to='organisations.organisation'),
        ),
    ]
