# Generated by Django 5.1.3 on 2024-11-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_sphere', '0002_alter_cricketteam_country'),
        ('organisations', '0003_alter_organisation_country_alter_organisation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketteam',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cricket_teams', to='organisations.organisation'),
        ),
    ]
