# Generated by Django 5.1.3 on 2024-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_role_alter_person_role'),
        ('league_sphere', '0003_cricketplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketplayer',
            name='role',
        ),
        migrations.AddField(
            model_name='cricketplayer',
            name='role',
            field=models.ManyToManyField(help_text='The role of the player in the team.', related_name='player_role', to='common.role'),
        ),
    ]
