# Generated by Django 5.1.3 on 2024-11-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_sphere', '0004_remove_cricketplayer_role_cricketplayer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketteam',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='league_sphere.cricketplayer'),
        ),
        migrations.AlterField(
            model_name='cricketteam',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='league_sphere.cricketplayer'),
        ),
    ]
