# Generated by Django 5.1.3 on 2024-11-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_sphere', '0005_alter_cricketteam_captain_alter_cricketteam_players'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketplayer',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='The Organisation the player belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.organisation'),
        ),
    ]
