# Generated by Django 5.1.3 on 2024-11-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
    ]
